"""
Project Brief Template for Phase 3 Pipeline
"""

PROJECT_BRIEF_TEMPLATE = """# Project Brief Template

## Project Overview
**Project Name:** {project_name}
**App Type:** {archetype}
**Priority Level:** HIGH
**Estimated Complexity:** MEDIUM

## Market Research Summary
**Target Market:** {target_audience}
**Competitive Landscape:** {competitors}
**Market Opportunity:** Based on market research and analysis
**User Personas:** Primary users and their needs

## UX Patterns & User Expectations
**Primary User Journey:** User flow and interaction patterns
**Key UX Patterns:** Common patterns users expect
**Mobile vs Desktop:** Responsive design requirements
**Accessibility Requirements:** WCAG compliance level needed

## Technical Requirements
**Frontend Stack:** {tech_stack}
**Backend Stack:** FastAPI/Express with proper architecture
**Database:** PostgreSQL/MongoDB with optimized schema
**AI/ML Integration:** {api_sources}
**Third-party APIs:** {data_sources}

## Core Features (MVP)
1. **Core Feature 1:** Essential functionality for MVP
2. **Core Feature 2:** Key user interactions
3. **Core Feature 3:** Data management and display
4. **Core Feature 4:** Integration with external services

## Advanced Features (Future)
1. **Advanced Feature 1:** Enhanced functionality
2. **Advanced Feature 2:** Premium features

## Data Requirements
**Data Sources:** {data_sources}
**Data Models:** Key entities and relationships
**Data Flow:** How data moves through the system

## Integration Points
**Authentication:** Clerk/Auth.js integration
**Payment Processing:** Stripe integration if applicable
**External Services:** Email, file storage, etc.
**AI Services:** {api_sources}

## Performance Requirements
**Response Time:** < 2 seconds for API calls
**Scalability:** Handle concurrent users efficiently
**Caching Strategy:** Redis for session and data caching

## Security Considerations
**Data Protection:** Secure handling of user data
**API Security:** Rate limiting, authentication, authorization
**Compliance:** GDPR compliance for user data

## Deployment & DevOps
**Hosting Platform:** Vercel (frontend) + Render (backend)
**Environment Variables:** Proper configuration management
**CI/CD Pipeline:** Automated deployment strategy

## Success Metrics
**User Engagement:** Active users and session duration
**Performance KPIs:** Response times and error rates
**Business Metrics:** User growth and retention

## Risk Assessment
**Technical Risks:** Integration complexity and API dependencies
**Market Risks:** User adoption and competition
**Mitigation Strategies:** Robust error handling and fallbacks

## Development Timeline
**Phase 1 (MVP):** Core features - 1-2 weeks
**Phase 2 (Enhancement):** Advanced features - 1-2 weeks
**Phase 3 (Optimization):** Performance and polish - 1 week

## Claude Coding Instructions
**App Type:** {archetype}
**Boilerplate Template:** Use appropriate template for {archetype}
**Special Instructions:** Follow best practices for {tech_stack}
**Integration Priority:** Start with core features, then add integrations

---
**Research Date:** {research_date}
**Researcher:** MarketResearcher Agent
**Confidence Level:** HIGH
**Additional Notes:** Generated by AI pipeline for automated development
"""
